/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Admin;

import DTO.NhanVien;
import GUI.Login.Login;
import GUI.QuanLy.GioiThieu;
import GUI.QuanLy.QuanLyGiay;
import GUI.QuanLy.QuanLyHoaDon;
import GUI.QuanLy.QuanLyNhanVien;
import GUI.QuanLy.QuanLyPhieuNhap;
import GUI.QuanLy.ThongKe;
import GUI.QuanLy.TrangChu;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class Admin extends javax.swing.JFrame {

    JPanel trangchu = null;
    JPanel quanlygiay = null;
    JPanel quanlyphieunhap = null;
    JPanel quanlyhoadon = null;
    JPanel quanlynhanvien = null;
    NhanVien nhanvien = null;

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        initialzation();
        performEvent();
    }

    public Admin(NhanVien nv) {
        setNhanvien(nv);
        initComponents();
        initialzation();
        performEvent();

    }

    public NhanVien getNhanvien() {
        return nhanvien;
    }

    public void setNhanvien(NhanVien nhanvien) {
        this.nhanvien = nhanvien;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        leftMenu = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        nameStaff = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftMenu.setBackground(new java.awt.Color(255, 255, 255));
        leftMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Icon/shoes.png"))); // NOI18N
        jButton1.setText("Quản Lý Giày");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        leftMenu.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 330, 78));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 102));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Icon/staff_60px.png"))); // NOI18N
        jButton2.setText("Quản Lý Nhân Viên");
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        leftMenu.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 330, 78));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 153, 102));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Icon/receipt_and_change_48px.png"))); // NOI18N
        jButton3.setText("Quản Lý Phiếu Nhập");
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        leftMenu.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 330, 78));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 153, 102));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Icon/bill_48px.png"))); // NOI18N
        jButton4.setText("Quản Lý Hóa Đơn");
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        leftMenu.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 330, 78));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 153, 102));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Icon/line_chart_48px.png"))); // NOI18N
        jButton5.setText("Thống Kê");
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        leftMenu.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 330, 78));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 153, 102));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Icon/home_48px.png"))); // NOI18N
        jButton6.setText("Trang Chủ");
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        leftMenu.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 78));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 153, 102));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Icon/questions_48px.png"))); // NOI18N
        jButton7.setText("Giới Thiệu");
        jButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        leftMenu.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 330, 78));

        background.add(leftMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, 510));

        header.setBackground(new java.awt.Color(0, 153, 102));

        nameStaff.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        nameStaff.setForeground(new java.awt.Color(255, 255, 255));
        nameStaff.setText("Tên Nhân Viên");

        exitBtn.setBackground(new java.awt.Color(255, 0, 0));
        exitBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Icon/logout_rounded_left_52px.png"))); // NOI18N
        exitBtn.setText("Đăng Xuất");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(nameStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 537, Short.MAX_VALUE)
                .addComponent(exitBtn))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameStaff)
                    .addComponent(exitBtn))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        background.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 50));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        background.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 1010, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 1340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel content;
    private javax.swing.JButton exitBtn;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel leftMenu;
    private javax.swing.JLabel nameStaff;
    // End of variables declaration//GEN-END:variables

    private void initialzation() {
        this.setLocationRelativeTo(null);
        if (nhanvien != null) {
            nameStaff.setText("Tên Nhân Viên : " + nhanvien.getTenNhanVien());
        }
        //Them trang chu
        trangchu = new TrangChu();
        addJPanelToContent(trangchu);
    }

    private void performEvent() {
        ActionListener ac = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String right = nhanvien.getQuyen().toLowerCase();
                switch (e.getActionCommand()) {
                    case "Trang Chủ": {
                        trangchu = new TrangChu();
                        addJPanelToContent(trangchu);
                        break;
                    }
                    case "Quản Lý Giày": {
                        quanlygiay = new QuanLyGiay();
                        addJPanelToContent(quanlygiay);
                        break;
                    }
                    case "Quản Lý Nhân Viên": {
                        if(right.compareTo("admin") != 0){
                            JOptionPane.showMessageDialog(null, "Bạn không có quyền sử dụng chức năng này");
                            return;
                        }
                        quanlynhanvien = new QuanLyNhanVien();
                        addJPanelToContent(quanlynhanvien);
                        break;
                    }
                    case "Quản Lý Phiếu Nhập": {
                        if(right.compareTo("admin") != 0){
                            JOptionPane.showMessageDialog(null, "Bạn không có quyền sử dụng chức năng này");
                            return;
                        }
                        quanlyphieunhap = new QuanLyPhieuNhap(nhanvien);
                        addJPanelToContent(quanlyphieunhap);
                        break;
                    }
                    case "Quản Lý Hóa Đơn": {
                        quanlyhoadon = new QuanLyHoaDon(nhanvien);
                        addJPanelToContent(quanlyhoadon);
                        break;
                    }
                    case "Giới Thiệu": {
                        JPanel p = new GioiThieu();
                        p.setVisible(true);
                        addJPanelToContent(p);
                        break;
                    }
                    case "Thoat": {
                        new Login().setVisible(true);
                        dispose();
                        break;
                    }
                    
                    case "Thống Kê":{
                        if(right.compareTo("admin") != 0){
                            JOptionPane.showMessageDialog(null, "Bạn không có quyền sử dụng chức năng này");
                            return;
                        }
                        new ThongKe().setVisible(true);
                        break;
                    }
                }
            }
        };

        for (Component c : leftMenu.getComponents()) {
            if (c instanceof JButton) {
                ((JButton) c).addActionListener(ac);
                ((JButton) c).setActionCommand(((JButton) c).getActionCommand());
            }
        }
        
        ((TrangChu)trangchu).addActionListennerHome(ac);

        exitBtn.addActionListener(ac);
        exitBtn.setActionCommand("Thoat");
    }

    public void addJPanelToContent(JPanel p) {
        content.removeAll();
        content.revalidate();
        content.repaint();
        p.setSize(1010, 590);
        p.setVisible(true);
        content.add(p);
    }
}
