/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.QuanLy;

import BUS.GiayBUS;
import ChucNangKhac.ChucNang;
import ChucNangKhac.tableFunc;
import DTO.Giay;
import com.sun.org.apache.bcel.internal.generic.AALOAD;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class QuanLyGiay extends javax.swing.JPanel {
    DefaultTableModel defaults = null;
    GiayBUS giaybus = new GiayBUS();
    /**
     * Creates new form TrangChu
     */
    public QuanLyGiay() {
        initComponents();
        initlization();
        performEvent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        searchInput = new javax.swing.JTextField();

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table);

        background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 79, 960, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 51));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Icon/edit_48px.png"))); // NOI18N
        jButton2.setText("Sửa");
        background.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 200, -1));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 153, 51));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Icon/sync_60px.png"))); // NOI18N
        jButton4.setText("Làm mới");
        background.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 200, -1));

        searchInput.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        background.add(searchInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 410, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searchInput;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    private void initlization() {
        initTable();
        loadTableData();
        searchInput.setBackground(new Color(0,0,0,0));
        searchInput.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(53,167,156)));
    }

    private void performEvent() {
        ActionListener ac = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                switch(e.getActionCommand()){
                    case "Sửa":{
                        new SuaGiay().setVisible(true);
                        break;
                    }
                    case "Làm mới":{
                        loadTableData();
                        JOptionPane.showMessageDialog(null, "Đã hiển thị lại");
                        searchInput.setText("");
                        break;
                    }
                }
            }
        };
        
        for(Component c : background.getComponents()){
            if(c instanceof JButton){
                ((JButton)c).addActionListener(ac);
                ((JButton)c).setActionCommand(((JButton)c).getActionCommand());
            }
        }
        
        searchInput.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent e) {
                String input = ChucNang.convertTextToEnglish(searchInput.getText());
                ArrayList<Giay> data = giaybus.searchGiayByKey(input);
                loadTableData(data);
            }
        });
    }

    private void initTable() {
        String []header = {"Mã Giày","Tên Giày","Mã NSX","Mã Loại","Size","Màu Sắc","Giá Thành","Trạng Thái"};
        defaults = (DefaultTableModel)table.getModel();
        
        for(String s : header){
            defaults.addColumn(s);
        }
        
        table.setRowHeight(25);
    }

    private void loadTableData() {
        tableFunc.removeAllTable(table);
        defaults = (DefaultTableModel)table.getModel();
        ArrayList<Giay> data = giaybus.getAllData();
        for(Giay g : data){
            Object[] obj = {
              g.getMaGiay(),
                g.getTenGiay(),
                g.getMaNSX(),
                g.getMaLoai(),
                g.getSize(),
                g.getMauSac(),
                g.getGiaThanh(),
                g.isTrangThai()
            };
            defaults.addRow(obj);
        }
    }
    
    private void loadTableData(ArrayList<Giay> data) {
        tableFunc.removeAllTable(table);
        defaults = (DefaultTableModel)table.getModel();
        for(Giay g : data){
            Object[] obj = {
              g.getMaGiay(),
                g.getTenGiay(),
                g.getMaNSX(),
                g.getMaLoai(),
                g.getSize(),
                g.getMauSac(),
                g.getGiaThanh(),
                g.isTrangThai()
            };
            defaults.addRow(obj);
        }
    }
}
