/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.QuanLy;

import BUS.HoaDonBUS;
import ChucNangKhac.tableFunc;
import DTO.HoaDon;
import DTO.NhanVien;
import DTO.PhieuNhap;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class QuanLyHoaDon extends javax.swing.JPanel {

    HoaDonBUS hdbus = new HoaDonBUS();
    NhanVien nhanvien = null;
    DefaultTableModel defaults = null;

    /**
     * Creates new form TrangChu
     */
    public QuanLyHoaDon() {
        initComponents();
    }

    public QuanLyHoaDon(NhanVien nv) {
        setNhanvien(nv);
        initComponents();
        performEvent();
        initialization();
    }

    public NhanVien getNhanvien() {
        return nhanvien;
    }

    public void setNhanvien(NhanVien nhanvien) {
        this.nhanvien = nhanvien;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table);

        background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 79, 960, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 153, 102));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Icon/sync_60px.png"))); // NOI18N
        jButton3.setText("Làm mới");
        background.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 200, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Icon/more_details_48px.png"))); // NOI18N
        jButton1.setText("Xem Chi Tiết");
        background.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 102));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Icon/plus_48px.png"))); // NOI18N
        jButton2.setText("Thêm");
        background.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    private void performEvent() {
        ActionListener ac = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                switch (e.getActionCommand()) {
                    case "Thêm": {
                        new ThemHoaDon(nhanvien).setVisible(true);
                        break;
                    }
                    case "Xem Chi Tiết": {
                        int select = table.getSelectedRow();
                        if (select < 0) {
                            JOptionPane.showMessageDialog(null, "Vui lòng chọn Phiếu Nhập để xem chi tiết");
                            return;
                        }
                        String id = String.valueOf(table.getValueAt(select, 0));
                        
                        new XemChiTietHoaDon(id).setVisible(true);
                        break;
                    }
                    case "Làm mới": {
                        loadTableData();
                        JOptionPane.showMessageDialog(null, "Đã hiển thị tất cả");
                        break;
                    }
                }
            }
        };
        for (Component c : background.getComponents()) {
            if (c instanceof JButton) {
                ((JButton) c).addActionListener(ac);
                ((JButton) c).setActionCommand(((JButton) c).getActionCommand());
            }
        }
    }

    private void initTable() {
        String[] header = {"Mã Hóa Đơn", "Mã Nhân Viên", "Ngày Lập"};
        defaults = (DefaultTableModel) table.getModel();

        for (String s : header) {
            defaults.addColumn(s);
        }

        table.setRowHeight(25);
    }

    private void loadTableData() {
        tableFunc.removeAllTable(table);
        defaults = (DefaultTableModel) table.getModel();
        ArrayList<HoaDon> data = hdbus.getAllData();
        for (HoaDon hd : data) {
            Object[] obj = {
                hd.getMaHoaDon(),
                hd.getMaNhanVien(),
                hd.getNgayXuat().toString()
            };
            defaults.addRow(obj);
        }
    }

    private void loadTableData(ArrayList<HoaDon> data) {
        tableFunc.removeAllTable(table);
        defaults = (DefaultTableModel) table.getModel();

        for (HoaDon hd : data) {
            Object[] obj = {
                hd.getMaHoaDon(),
                hd.getMaNhanVien(),
                hd.getNgayXuat().toString()
            };
            defaults.addRow(obj);
        }
    }

    private void initialization() {
        initTable();
        loadTableData();
    }
}
