/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.QuanLy;

import BUS.NhanVienBUS;
import ChucNangKhac.ChucNang;
import DTO.NhanVien;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;


public class SuaNhanVien extends javax.swing.JFrame {

    NhanVienBUS nvbus = new NhanVienBUS();

    /**
     * Creates new form SuaNhanVien
     */
    public SuaNhanVien() {
        initComponents();
        initialization();
        performEvent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        Size = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pass = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        id = new javax.swing.JComboBox<>();
        name = new javax.swing.JTextField();
        right = new javax.swing.JComboBox<>();
        status = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Tên Nhân Viên:");
        background.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        address.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        background.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 370, -1));

        update.setBackground(new java.awt.Color(255, 255, 255));
        update.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        update.setForeground(new java.awt.Color(0, 204, 0));
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Icon/tick_box_32px.png"))); // NOI18N
        update.setText("Cập Nhật");
        background.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 630, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sửa Nhân Viên");
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 608, 77));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Địa Chỉ");
        background.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Mã Nhân Viên :");
        background.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("Ngày Sinh :");
        background.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("Tên Đăng Nhập");
        background.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        user.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        background.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 370, -1));

        phone.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        background.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 370, -1));

        Size.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Size.setText("SĐT");
        background.add(Size, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setText("Mật Khẩu");
        background.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        pass.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        background.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 370, -1));

        date.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        background.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 370, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("Quyền");
        background.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));

        id.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        background.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 370, -1));

        name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        background.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 164, 370, -1));

        right.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        background.add(right, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, 370, -1));

        status.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        background.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, 370, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setText("Trạng Thái");
        background.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuaNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Size;
    private javax.swing.JTextField address;
    private javax.swing.JPanel background;
    private javax.swing.JTextField date;
    private javax.swing.JComboBox<String> id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField name;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField phone;
    private javax.swing.JComboBox<String> right;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JButton update;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables

    private void initialization() {
        setLocationRelativeTo(null);
        loadCombobox();
        setDefaultCloseOperation(HIDE_ON_CLOSE);

    }

    private void performEvent() {
        id.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (id.getSelectedIndex() <= 0) {
                    reset();
                    return;
                }
                NhanVien nv = nvbus.getStaffById(String.valueOf(id.getSelectedItem()));
                displayStaff(nv);
            }
        });
        
        update.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if(id.getSelectedIndex() == 0){
                    JOptionPane.showMessageDialog(null, "Bạn chưa chọn Nhân viên để sửa");
                    return;
                }
                if(checkInput() == false) return;
                NhanVien nv = new NhanVien(
                        String.valueOf(id.getSelectedItem()),
                        name.getText(),
                        LocalDate.parse(date.getText(),DateTimeFormatter.ofPattern("yyyy-MM-dd")),
                        address.getText(),
                        phone.getText(),
                        user.getText(),
                        pass.getText(),
                        (right.getSelectedIndex() == 0) ? "Admin":"NhanVien",
                        (status.getSelectedIndex() == 0) ? true:false
                );
                
                if(nvbus.updateStaff(nv)){
                    JOptionPane.showMessageDialog(null, "Sửa thành công");
                    reset();
                    return;
                }
                JOptionPane.showMessageDialog(null, "Không thể sửa");
                        
            }
        });
    }

    private void loadCombobox() {
        right.addItem("Admin");
        right.addItem("NhanVien");

        status.addItem("Hoạt động");
        status.addItem("Khoá");

        id.addItem("[Lựa Chọn]");
        ArrayList<NhanVien> data = nvbus.getAllData();
        for (NhanVien nv : data) {
            id.addItem(nv.getMaNhanVien());
        }
    }

    private void reset() {
        id.setSelectedIndex(0);
        name.setText("");
        date.setText("");
        address.setText("");
        phone.setText("");
        user.setText("");
        pass.setText("");
        right.setSelectedIndex(0);
        status.setSelectedIndex(0);
    }

    private void displayStaff(NhanVien nv) {
        name.setText(nv.getTenNhanVien());
        date.setText(nv.getNgaySinh().toString());
        address.setText(nv.getDiaChi());
        phone.setText(nv.getSDT());
        user.setText(nv.getUserName());
        pass.setText(nv.getPassword());
        right.setSelectedItem(nv.getQuyen());
        status.setSelectedIndex((nv.isTrangThai()) ? 0:1);
    }
    
    private boolean checkInput(){
        if(name.getText().compareTo("") == 0){
            JOptionPane.showMessageDialog(null, "Chưa nhập tên Nhân Viên");
            return false;
        }
        if(date.getText().compareTo("") == 0){
            JOptionPane.showMessageDialog(null, "Chưa nhập ngày sinh Nhân Viên");
            return false;
        }
        try {
            LocalDate.parse(date.getText(), DateTimeFormatter.ofPattern("yyyy-MM-dd"));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ngày sinh Nhân Viên phải có dạng yyyy-mm-dd");
            return false;
        }
        
        if(address.getText().compareTo("") == 0){
            JOptionPane.showMessageDialog(null, "Chưa nhập địa chỉ Nhân Viên");
            return false;
        }
        if(phone.getText().compareTo("") == 0){
            JOptionPane.showMessageDialog(null, "Chưa nhập SĐT Nhân Viên");
            return false;
        }
        if(phone.getText().length() != 10){
            JOptionPane.showMessageDialog(null, "SĐT phải có 10 số");
            return false;
        }
        try {
            Integer.valueOf(phone.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "SĐT không hợp lệ");
            return false;
        }
        if(user.getText().compareTo("") == 0){
            JOptionPane.showMessageDialog(null, "Chưa nhập Tên đăng nhập Nhân Viên");
            return false;
        }
        
        if(pass.getText().compareTo("") == 0){
            JOptionPane.showMessageDialog(null, "Chưa nhập SĐT Mật khẩu");
            return false;
        }
        if(ChucNang.isValidPass(pass.getText()) == false){
            JOptionPane.showMessageDialog(null, "Mật khẩu không hợp lệ. Mật khẩu chỉ chứa chữ thường, chữ in hoa và số");
            return false;
        }
        return true;
    }
}
