/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI.QuanLy;

import BUS.GiayBUS;
import BUS.HoaDonBUS;
import BUS.NhanVienBUS;
import BUS.PhieuNhapBUS;


public class ThongKe extends javax.swing.JFrame {
    PhieuNhapBUS pnbus = new PhieuNhapBUS();
    HoaDonBUS hdbus = new HoaDonBUS();
    GiayBUS giayBUS = new GiayBUS();
    NhanVienBUS nvbus = new NhanVienBUS();
    /** Creates new form ThongKe */
    public ThongKe() {
        initComponents();
        ChucNangKhac.ThongKe.lineChart(pnbus.getDataChar(), "Thống kê Phiếu Nhập theo Tháng", "Tháng", "Tổng (VNĐ)", tkPhieuNhap);
        ChucNangKhac.ThongKe.lineChart(hdbus.getDataChar(), "Thống kê Hóa Đơn theo Tháng", "Tháng", "Tổng (triệu VNĐ)", tkHoaDon);
        ChucNangKhac.ThongKe.pieChart(giayBUS.getDataChar(), "Thống kê Giày theo số lượng", tkgiay);
        ChucNangKhac.ThongKe.barChart(nvbus.getDataChar(), "Thống kê nhân viên theo năm sinh", "Năm Sinh", "Số Lượng", tkNhanVien);
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        tkgiay = new javax.swing.JPanel();
        tkNhanVien = new javax.swing.JPanel();
        tkHoaDon = new javax.swing.JPanel();
        tkPhieuNhap = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tkgiay.setLayout(new java.awt.BorderLayout());
        background.add(tkgiay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 671, 360));

        tkNhanVien.setLayout(new java.awt.BorderLayout());
        background.add(tkNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 369, 671, 370));

        tkHoaDon.setLayout(new java.awt.BorderLayout());
        background.add(tkHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 671, 360));

        tkPhieuNhap.setLayout(new java.awt.BorderLayout());
        background.add(tkPhieuNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 370, 671, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel tkHoaDon;
    private javax.swing.JPanel tkNhanVien;
    private javax.swing.JPanel tkPhieuNhap;
    private javax.swing.JPanel tkgiay;
    // End of variables declaration//GEN-END:variables

}
