/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.QuanLy;

import BUS.ChiTietHoaDonBUS;
import BUS.ChiTietPhieuNhapBUS;
import BUS.GiayBUS;
import BUS.HoaDonBUS;
import BUS.NhaCungCapBUS;
import BUS.NhanVienBUS;
import BUS.PhieuNhapBUS;
import ChucNangKhac.ChucNang;
import ChucNangKhac.tableFunc;
import DTO.ChiTietHoaDon;
import DTO.ChiTietPhieuNhap;
import DTO.HoaDon;
import DTO.PhieuNhap;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;


public class XemChiTietPhieuNhap extends javax.swing.JFrame {
    DefaultTableModel defaults = null;
    ArrayList<ChiTietPhieuNhap> dataCTPN = new ArrayList<>();
    ChiTietPhieuNhapBUS ctpnbus = new ChiTietPhieuNhapBUS();
    GiayBUS giaybus = new GiayBUS();
    PhieuNhapBUS pnbus = new PhieuNhapBUS();
    NhanVienBUS nvbus = new NhanVienBUS();
    NhaCungCapBUS nccbus = new NhaCungCapBUS();
    /**
     * Creates new form XemChiTietHoaDon
     */
    public XemChiTietPhieuNhap() {
        initComponents();
    }
    
    public XemChiTietPhieuNhap(String id) {
        initComponents();
        dataCTPN = ctpnbus.getPNById(id);
        initialization(id);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameStaff = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        sumPrice = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        date = new javax.swing.JLabel();
        supplier = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chi Tiết Phiếu Nhập");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 996, 90));

        nameStaff.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        nameStaff.setText("Tên Nhà Cung Cấp :");
        jPanel1.add(nameStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 550, -1));

        id.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        id.setText("Mã Phiếu Nhập :");
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 350, -1));

        sumPrice.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        sumPrice.setForeground(new java.awt.Color(255, 0, 51));
        sumPrice.setText("Tổng :");
        jPanel1.add(sumPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, 530, -1));

        table.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 870, 364));

        date.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        date.setText("Ngày Lập :");
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 530, -1));

        supplier.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        supplier.setText("Tên Nhân Viên :");
        jPanel1.add(supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 550, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XemChiTietPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XemChiTietPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XemChiTietPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XemChiTietPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XemChiTietPhieuNhap("PN00002").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameStaff;
    private javax.swing.JLabel sumPrice;
    private javax.swing.JLabel supplier;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
    
    private void initTable() {
        String[] header = {"Mã Giày", "Tên Giày", "Số Lượng","Giá"};
        defaults = (DefaultTableModel) table.getModel();
        for (String s : header) {
            defaults.addColumn(s);
        }

        table.setRowHeight(25);
    }

    private void loadTableData() {
        tableFunc.removeAllTable(table);
        for (ChiTietPhieuNhap ct : dataCTPN) {
            Object[] obj = {
                ct.getMaGiay(),
                giaybus.getNameById(ct.getMaGiay()),
                ct.getSoLuong(),
                ChucNang.convetNumberToMoney(String.valueOf(giaybus.getPriceById(ct.getMaGiay())))
            };
            defaults.addRow(obj);
        }
        computePrice();
    }

    private void computePrice() {
        int sum = 0;
        for(ChiTietPhieuNhap ct :dataCTPN){
            sum += ct.getSoLuong() * giaybus.getPriceById(ct.getMaGiay());
        }
        sumPrice.setText("Tổng : " + ChucNang.convetNumberToMoney(String.valueOf(sum)) + " VNĐ");
    }

    private void initialization(String id) {
        setLocationRelativeTo(null);
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        
        initTable();
        loadTableData();
        
        PhieuNhap pn = pnbus.getPNById(id);
        
        this.id.setText("Mã Hóa Đơn : " + pn.getMaPhieuNhap());
        nameStaff.setText("Tên Nhân Viên : " + nvbus.getNameById(pn.getMaNhanVien()));
        date.setText("Ngày Nhập :" + pn.getNgayNhap().toString());
        supplier.setText("Tên Nhà Cung Cấp : " + nccbus.getNameById(pn.getMaNhaCungCap()));
    }
}
